version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      dev-tooling:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'vitest*'
          - '@testing-library/*'
          - 'playwright*'
          - '@playwright/*'
          - 'husky'
          - 'lint-staged'
      next-ecosystem:
        patterns:
          - 'next'
          - 'react'
          - 'react-dom'
          - '@types/react*'
